Repository ddan-dda-ra/ddan-ddan-android, pull requests merged in 2024-11, with the labels that each got.

#41 [FEAT/#35] erroer screen 구현
  app/src/main/java/com/ddanddan/ddanddan/presentation/MainScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/error/ErrorScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeContract.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeViewModel.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/collect/CollectViewModel.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/collect/PetCollectionContract.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/collect/PetCollectionScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/navigation/Navigation.kt
  app/src/main/res/drawable/ic_error.xml
Labels: 🦖 강민

#46 [FEAT/#45] 워치 데이터 전송, 암호화 관련 유틸 코드 추가
  app/src/main/java/com/ddanddan/ddanddan/ext/ContextExt.kt
  app/src/main/java/com/ddanddan/ddanddan/util/SecurityUtils.kt
  app/src/main/java/com/ddanddan/ddanddan/util/WatchUtils.kt
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/java/com/ddanddan/convention/src/main/kotlin/plugins/AndroidApplicationPlugin.kt
  gradle/libs.versions.toml
Labels: ☘️우남

#49 [FEAT/#38] 홈 화면 펫 분기처리 추가
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeBottomScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/util/Extension.kt
  app/src/main/res/drawable/ic_bg_cat.xml
  app/src/main/res/drawable/ic_bg_dog.xml
  app/src/main/res/drawable/ic_bg_hamster.xml
  app/src/main/res/drawable/ic_bg_penguin.xml
  app/src/main/res/raw/motion_cat_level4_default.json
Labels: 🦖 강민

#52 [FEAT/#51] 펫 종류, 레벨 별 분기처리
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/collect/PetCollectionScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/reward/level/LevelUpScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/reward/pet/NewPetScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/util/Extension.kt
  app/src/main/java/com/ddanddan/ddanddan/util/PetTypeExtension.kt
  app/src/main/res/drawable/ic_cat.xml
  app/src/main/res/drawable/ic_cat_level1.xml
  app/src/main/res/drawable/ic_cat_level2.xml
  app/src/main/res/drawable/ic_cat_level3.xml
  app/src/main/res/drawable/ic_cat_level4.xml
  app/src/main/res/drawable/ic_cat_level5.xml
  app/src/main/res/drawable/ic_dog_level1.xml
  app/src/main/res/drawable/ic_dog_level2.xml
  app/src/main/res/drawable/ic_dog_level3.xml
  app/src/main/res/drawable/ic_dog_level4.xml
  app/src/main/res/drawable/ic_dog_level5.xml
  app/src/main/res/drawable/ic_hamster_level1.xml
  app/src/main/res/drawable/ic_hamster_level2.xml
  app/src/main/res/drawable/ic_hamster_level3.xml
  app/src/main/res/drawable/ic_hamster_level4.xml
  app/src/main/res/drawable/ic_hamster_level5.xml
  app/src/main/res/drawable/ic_penguin_level1.xml
  app/src/main/res/drawable/ic_penguin_level2.xml
  app/src/main/res/drawable/ic_penguin_level3.xml
  app/src/main/res/drawable/ic_penguin_level4.xml
  app/src/main/res/drawable/ic_penguin_level5.xml
  app/src/main/res/raw/motion_cat_level4_default.json
  app/src/main/res/raw/motion_cat_level5_default.json
Labels: 🦖 강민

#54 [FEAT/#53] 애니메이션 툴팁 컴포넌트 구현
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeContract.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeViewModel.kt
  core/ui/src/main/java/com/ddanddan/ui/compose/component/DDanAnimationTooltip.kt
  core/ui/src/main/java/com/ddanddan/ui/ext/ComposeUtilExt.kt
  core/ui/src/main/res/drawable-hdpi/ic_tooltip.9.png
  core/ui/src/main/res/drawable-mdpi/ic_tooltip.9.png
  core/ui/src/main/res/drawable-xhdpi/ic_tooltip.9.png
  core/ui/src/main/res/drawable-xxhdpi/ic_tooltip.9.png
  core/ui/src/main/res/drawable-xxxhdpi/ic_tooltip.9.png
Labels: 🦖 강민

#56 [FEAT/#55] 홈화면 리컴포지션 최적화
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeTopScreen.kt
  core/ui/src/main/java/com/ddanddan/ui/compose/Type.kt
  core/ui/src/main/java/com/ddanddan/ui/compose/component/DDanAnimationTooltip.kt
Labels: 🦖 강민

#61 [FEAT/#60] 자동로그인 활성화
  app/src/main/java/com/ddanddan/ddanddan/MyApp.kt
  app/src/main/java/com/ddanddan/ddanddan/di/AppModule.kt
  app/src/main/java/com/ddanddan/ddanddan/di/RepositoryModule.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/signin/SignInActivity.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/signin/SignInViewModel.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/splash/SplashActivity.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/ddanddan/ddanddan/util/provider/KakaoProvider.kt
  core/data/src/main/java/com/ddanddan/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/ddanddan/domain/repository/AuthRepository.kt
Labels: 🧩 세연

#44 [Feat/#12] 세팅 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddanddan/ddanddan/presentation/MainActivity.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/MainScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/home/HomeViewModel.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/navigation/Navigation.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/EditTargetScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/OnAgreenScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/SettingContract.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/SettingIntent.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/SettingScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/WebviewScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/nickname/EditNickNameScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/signout/SignOutFirstScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/signout/SignOutSecondScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/target/EditTargetScreen.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/viewModel/SettingUiModel.kt
  app/src/main/java/com/ddanddan/ddanddan/presentation/setting/viewModel/SettingViewModel.kt
  app/src/main/res/drawable/btn_system_minus_fill.xml
  app/src/main/res/drawable/ic_check_box_default.xml
  app/src/main/res/drawable/ic_check_box_select.xml
  app/src/main/res/drawable/ic_signout_img.xml
  app/src/main/res/drawable/ic_signout_main.xml
  app/src/main/res/drawable/icon_radio_check_non.xml
  app/src/main/res/drawable/icon_radio_check_on.xml
  app/src/main/res/drawable/icon_system_plus.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/java/com/ddanddan/convention/src/main/kotlin/Constants.kt
  core/data/src/main/java/com/ddanddan/data/datasource/remote/RemoteUserDataSource.kt
  core/data/src/main/java/com/ddanddan/data/repository/UserRepositoryImpl.kt
  core/data/src/main/java/com/ddanddan/data/service/UserService.kt
  core/domain/src/main/java/com/ddanddan/domain/repository/UserRepository.kt
  core/domain/src/main/java/com/ddanddan/domain/usecase/DeleteUserUseCase.kt
  core/domain/src/main/java/com/ddanddan/domain/usecase/DisableAutoLoginUseCase.kt
  core/ui/src/main/java/com/ddanddan/ui/compose/component/DDanScaffold.kt
  core/ui/src/main/java/com/ddanddan/ui/compose/component/DDanTwoButtonDialog.kt
  core/ui/src/main/java/com/ddanddan/ui/ext/ViewModelExt.kt
  core/ui/src/main/res/values/strings.xml
Labels: 🍀민서
